# Generated by Django 5.0.7 on 2024-08-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(default='', max_length=25)),
                ('project_description', models.TextField(default='')),
                ('image_main', models.ImageField(upload_to='project-images')),
                ('image_1', models.ImageField(upload_to='project-images')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='project-images')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='project-images')),
            ],
        ),
    ]
