# Generated by Django 5.0.7 on 2024-08-18 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DelroyBrownPortfolio_projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectdetails',
            name='prog_language_used',
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='prog_languages_used',
            field=models.ManyToManyField(to='DelroyBrownPortfolio_projects.proglanguageused'),
        ),
    ]
