# Generated by Django 5.0.7 on 2024-08-18 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DelroyBrownPortfolio_projects', '0002_remove_projectdetails_prog_language_used_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proglanguageused',
            name='language_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
