# Generated by Django 5.0.7 on 2024-08-18 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DelroyBrownPortfolio_projects', '0003_alter_proglanguageused_language_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectdetails',
            old_name='project_description',
            new_name='project_description_long',
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='project_description_short',
            field=models.TextField(default=''),
        ),
    ]
