# Generated by Django 5.0.7 on 2024-08-18 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DelroyBrownPortfolio_projects', '0004_rename_project_description_projectdetails_project_description_long_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetails',
            name='link_to_project',
            field=models.URLField(blank=True, null=True),
        ),
    ]
